#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

set -e
umask 022

# Define the default variables
sleep=0

# Define the default glaucus directory (which is normally the parent directory
# for both the cerata and the radula).
GLAD=$PWD/..
# Define the default location for cerata (testing atm)
CERD=$GLAD/cerata

# Standard output function
# Opens the radula (mouth)
rad_open() {
  [ $sleep = 0 ] && printf "\033[0;34m~~\033[0m $1\n" || printf "$1\n"
}

# Standard error function
# Closes the radula (mouth)
rad_close() {
  [ $sleep = 0 ] && printf "\033[0;31m~~\033[0m $1\n" || printf "$1\n"
  exit 1
}

# Information functions
rad_license() {
  rad_open 'Copyright (c) 2018-2020, Firas Khalil Khana'
  rad_open 'Distributed under the terms of the ISC License'
}

rad_version() {
  rad_license

  rad_open
  rad_open "$0 version 0.4"
}

rad_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 (Flags)"
  rad_open
  rad_open 'Flags:'
  rad_open '\tb, -b, --behave \tPerform any of the following behaviors:'
  rad_open '\t                \tbootstrap, envenomate (default)'
  rad_open
  rad_open '\tg, -g, --genome \tDisplay current genome'
  rad_open '\th, -h, --help   \tDisplay this help message'
  rad_open '\tl, -l, --list   \tList available genomes and species'
  rad_open '\tq, -q, --quiet  \tDo not prefix output with ~~'
  rad_open '\t       --sleep  \tSame as --quiet'
  rad_open
  rad_open '\tr, -r, --require\tCheck if the host system has all required packages'
  rad_open '\ts, -s, --species\tDisplay current species'
  rad_open '\tv, -v, --version\tDisplay version number'
}

rad_behave_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 b (Options)"
  rad_open
  rad_open 'Options:'
  rad_open '\tb, bootstrap \tPerform bootstrap behavior'
  rad_open '\te, envenomate\tPerform envenomate behavior (default)'
}

rad_behave_bootstrap_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 b b (Options)"
  rad_open
  rad_open 'Options:'
  rad_open '\tr, require  \tCheck if the host system has all required packages'
  rad_open
  rad_open '\tc, chroot   \tBootstrap a cross compiled chroot environment'
  rad_open '\tt, toolchain\tBootstrap a cross compiler toolchain'
  rad_open '\tx, cross    \tBootstrap a cross compiled glaucus system (default)'
}

rad_behave_envenomate_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 b e (Options) [Cerata]"
  rad_open
  rad_open 'Options:'
  rad_open "\tn, nom, name                     \tDisplay ceras's name"
  rad_open "\tv, ver, version                  \tDisplay ceras's version"
  rad_open "\tu, url, source                   \tDisplay ceras's source"
  rad_open "\ts, sum, checksum, sha512sum      \tDisplay ceras's sha512sum"
  rad_open "\ty, cys, cyst, cysts              \tDisplay ceras's cyst(s)"
  rad_open "\tc, cnt, concentrate, concentrates\tDisplay ceras's concentrate(s)"
  rad_open "\tl, lic, license, licenses        \tDisplay ceras's license(s)"
}

# Action functions
rad_behave_bootstrap_require() {
  rad_open 'Checking if the host system has all required packages...'
  rad_open
  rad_open "bash:     \t$(bash --version | sed 1q | cut -d' ' -f4)"
  rad_open "bc:       \t$(bc --version | sed 1q | cut -d' ' -f2)"
  rad_open "binutils: \t$(ld --version | sed 1q | cut -d' ' -f4)"
  rad_open "bison:    \t$(bison --version | sed 1q | cut -d' ' -f4)"
  rad_open "bzip2:    \t$(bzip2 --version 2>&1 < /dev/null | sed 1q | cut -d' ' -f8 | sed s/,//)"
  rad_open "ccache:   \t$(ccache --version | sed 1q | cut -d' ' -f3)"
  rad_open "coreutils:\t$(ls --version | sed 1q | cut -d' ' -f4)"
  rad_open "diffutils:\t$(diff --version | sed 1q | cut -d' ' -f4)"
  rad_open "findutils:\t$(find --version | sed 1q | cut -d' ' -f4)"
  rad_open "g++:      \t$(g++ --version | sed 1q | cut -d' ' -f3)"
  rad_open "gawk:     \t$(gawk --version | sed 1q | cut -d' ' -f3 | sed s/,//)"
  rad_open "gcc:      \t$(gcc --version | sed 1q | cut -d' ' -f3)"
  rad_open "git:      \t$(git --version | cut -d' ' -f3)"
  rad_open "glibc:    \t$(/lib/libc.so.6 | sed 1q | cut -d' ' -f9 | sed s/\.$//)"
  rad_open "grep:     \t$(grep --version | sed 1q | cut -d' ' -f4)"
  rad_open "gzip:     \t$(gzip --version | sed 1q | cut -d' ' -f2)"
  rad_open "linux:    \t$(uname -r)"
  rad_open "lzip:     \t$(lzip --version | sed 1q | cut -d' ' -f2)"
  rad_open "m4:       \t$(m4 --version | sed 1q | cut -d' ' -f4)"
  rad_open "make:     \t$(make --version | sed 1q | cut -d' ' -f3)"
  rad_open "patch:    \t$(patch --version | sed 1q | cut -d' ' -f3)"
  rad_open "perl:     \t$(perl -V:version | cut -d"'" -f2)"
  rad_open "rsync:    \t$(rsync --version | sed 1q | cut -d' ' -f4)"
  rad_open "sed:      \t$(sed --version | sed 1q | cut -d' ' -f4)"
  rad_open "tar:      \t$(tar --version | sed 1q | cut -d' ' -f4)"
  rad_open "texinfo:  \t$(makeinfo --version | sed 1q | cut -d' ' -f4)"
  rad_open "xz:       \t$(xz --version | sed 1q | cut -d' ' -f4)"
  rad_open "zstd:     \t$(zstd --version | cut -d' ' -f7 | sed 's/,$//')"
}

rad_behave_bootstrap_arch() {
  case $genome in
    aarch64 | armv8-a | arm64)
      export ARCH=aarch64

      export CARCH=--with-gcc-arch=armv8-a

      export FARCH='-mabi=lp64 -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -march=armv8-a -mtune=generic'

      export GCARCH='--with-arch=armv8-a --with-abi=lp64 --enable-fix-cortex-a53-835769 --enable-fix-cortex-a53-843419'
      export GPARCH="$SCRD/patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=$ARCH

      export LARCH=arm64
      export LCARCH=
      export LIARCH=arch/$LARCH/boot/Image

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    armv6zk | arm | bcm2835)
      export ARCH=armv6zk

      export CARCH=

      export FARCH="-mabi=aapcs-linux -march=$ARCH -mtune=arm1176jzf-s -mcpu=arm1176jzf-s -mfpu=vfpv2 -mfloat-abi=hard"

      export GCARCH="--with-arch=$ARCH --with-tune=arm1176jzf-s --with-abi=aapcs-linux --with-fpu=vfpv2 --with-float=hard"
      export GPARCH=

      export MARCH=arm

      export LARCH=$MARCH
      export LCARCH=bcm2835_
      export LIARCH=arch/$MARCH/boot/zImage

      export TGT=$ARCH-glaucus-linux-musleabihf
      ;;
    i686 | i386 | x86)
      export ARCH=i686

      export CARCH=--with-gcc-arch=$ARCH

      export FARCH="-march=$ARCH -mtune=generic -mabi=sysv"

      export GCARCH="--with-arch=$ARCH --with-tune=generic"
      export GPARCH=

      export MARCH=i386

      export LARCH=$MARCH
      export LCARCH=${MARCH}_
      export LIARCH=arch/x86/boot/bzImage

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    powerpc | pmac32 | ppc)
      export ARCH=powerpc

      export CARCH=

      export FARCH="-mcpu=$ARCH -msecure-plt"

      export GCARCH="--with-cpu=$ARCH --enable-secureplt --without-long-double-128"
      export GPARCH=

      export MARCH=$ARCH

      export LARCH=$ARCH
      export LCARCH=pmac32_
      export LIARCH=vmlinux

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    powerpc64 | g5 | ppc64)
      export ARCH=powerpc64

      export CARCH=

      export FARCH="-mcpu=$ARCH -mabi=elfv2"

      export GCARCH="--with-cpu=$ARCH --with-abi=elfv2"
      export GPARCH="$SCRD/patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=$ARCH

      export LARCH=powerpc
      export LCARCH=g5_
      export LIARCH=vmlinux

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    powerpc64le | powernv | ppc64le)
      export ARCH=powerpc64le

      export CARCH=

      export FARCH="-mcpu=$ARCH -mabi=elfv2"

      export GCARCH="--with-cpu=$ARCH --with-abi=elfv2"
      export GPARCH="$SCRD/patch 0 gcc glaucus 0001-pure64-for-powerpc64"

      export MARCH=powerpc64

      export LARCH=powerpc
      export LCARCH=powernv_
      export LIARCH=vmlinux

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    riscv64 | rv64imafdc | riscv)
      export ARCH=riscv64

      export CARCH=--with-gcc-arch=rv64imafdc

      export FARCH='-mabi=lp64d -march=rv64imafdc -mtune=rocket'

      export GCARCH='--with-arch=rv64imafdc --with-tune=rocket --with-abi=lp64d'
      export GPARCH="$SCRD/patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=$ARCH

      export LARCH=riscv
      export LCARCH=
      export LIARCH=arch/$LARCH/boot/Image

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    x86-64 | x86_64)
      export ARCH=x86-64

      export CARCH=--with-gcc-arch=$ARCH

      export FARCH="-march=$ARCH -mtune=generic -mabi=sysv"

      export GCARCH="--with-arch=$ARCH --with-tune=generic"
      export GPARCH="$SCRD/patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=x86_64

      export LARCH=$MARCH
      export LCARCH=${MARCH}_
      export LIARCH=arch/x86/boot/bzImage

      export TGT=$MARCH-glaucus-linux-musl
      ;;
    *)
      $0 l g
      exit 1
      ;;
  esac
}

rad_behave_bootstrap_flags() {
  # Some common flags in all species
  COMMON=-fcommon
  DEBUG=-g0
  FAT=-ffat-lto-objects
  LTO=-flto
  PIPE=-pipe
  STRIP=-s

  case $species in
    albino | libre)
      ;;
    atlanticus | performance)
      export SPCS=atlanticus

      case $genome in
        x86-64 | x86_64)
          ALIGN=-malign-data=cacheline
          FPMATH=-mfpmath=both
          TLS=-mtls-dialect=gnu2
          ;;
      esac
      DEVIRT=-fdevirtualize-at-ltrans
      EXPAND=-fvariable-expansion-in-unroller
      FINITE=-fno-finite-math-only
      GCSE='-fgcse-sm -fgcse-las'
      GRAPHITE='-fgraphite-identity -floop-nest-optimize'
      IPA=-fipa-pta
      IRA=-fira-loop-pressure
      MERGE=-fmerge-all-constants
      OFAST=-Ofast
      OPENMP=-fopenmp
      PGO='-ftracer -funroll-loops'
      PLT=-fno-plt
      SEMANTIC=-fno-semantic-interposition
      SMS='-fmodulo-sched -fmodulo-sched-allow-regmoves'

      export CFLAGS="$PIPE $OPENMP $DEBUG $OFAST $SMS $GCSE $IRA $IPA $GRAPHITE $MERGE $DEVIRT $SEMANTIC $EXPAND $LTO $PGO $STRIP $PLT $FARCH $TLS $FPMATH $ALIGN"

      export CFLAGSFAT="$(printf -- "$CFLAGS" | sed "s/$LTO/& $FAT/")"
      export CFLAGSFATNOCOMMON="$(printf -- "$CFLAGSFAT" | sed "s/$STRIP /&$COMMON /")"

      export CFLAGSFINITE="$(printf -- "$CFLAGS" | sed "s/$OFAST/& $FINITE/")"

      export CFLAGSNOCOMMON="$(printf -- "$CFLAGS" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSNOCOMMONNOLTO="$(printf -- "$CFLAGS" | sed -e "s/$STRIP /&$COMMON /" -e "s/$LTO //")"

      export CFLAGSNOFPMATHNOLTO="$(printf -- "$CFLAGS" | sed -e "s/ $FPMATH//" -e "s/$LTO //")"

      export CFLAGSNOIPANOLTO="$(printf -- "$CFLAGS" | sed -e "s/$IPA //" -e "s/$LTO //")"

      export CFLAGSNOLTO="$(printf -- "$CFLAGS" | sed "s/$LTO //")"
      export CFLAGSNOLTONOOPENMPNOPLT="$(printf -- "$CFLAGSNOLTO" | sed -e "s/$OPENMP //" -e "s/$PLT //")"

      export CFLAGSNOOPENMP="$(printf -- "$CFLAGS" | sed "s/$OPENMP //")"

      export CXXFLAGS="$CFLAGS"

      export LDFLAGS="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed $CFLAGS"

      export LDFLAGSNOOPENMP="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed $CFLAGSNOOPENMP"

      export LDFLAGSNORELRO="-Wl,--strip-all -Wl,--as-needed $CFLAGS"
      ;;
    bennettae | size)
      export SPCS=bennettae

      AUNWIND=-fno-asynchronous-unwind-tables
      DSECTS=-fdata-sections
      FSECTS=-ffunction-sections
      OMIT=-fomit-frame-pointer
      OS=-Os
      UNWIND=-fno-unwind-tables

      export CFLAGS="$PIPE $DEBUG $OS $OMIT $LTO $FSECTS $DSECTS $STRIP $UNWIND $AUNWIND $FARCH "

      export CFLAGSFAT="$(printf -- "$CFLAGS" | sed "s/$LTO/& $FAT/")"
      export CFLAGSFATNOCOMMON="$(printf -- "$CFLAGSFAT" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSFATNODSECTS="$(printf -- "$CFLAGSFAT" | sed "s/$DSECTS //")"

      export CFLAGSNODSECTS="$(printf -- "$CFLAGS" | sed "s/$DSECTS //")"

      export CFLAGSNOCOMMON="$(printf -- "$CFLAGS" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSNOCOMMONNOLTO="$(printf -- "$CFLAGS" | sed -e "s/$STRIP /&$COMMON /" -e "s/$LTO //")"

      export CFLAGSNOLTO="$(printf -- "$CFLAGS" | sed "s/$LTO //")"

      export CXXFLAGS="$CFLAGS"

      export LDFLAGS="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed -Wl,--gc-sections $CFLAGS"

      export LDFLAGSNORELRO="-Wl,--strip-all -Wl,--as-needed $CFLAGS"
      ;;
    marginatus | sane)
      export SPCS=marginatus

      DEVIRT=-fdevirtualize-at-ltrans
      GRAPHITE='-fgraphite-identity -floop-nest-optimize'
      IPA=-fipa-pta
      O3=-O3
      SEMANTIC=-fno-semantic-interposition

      export CFLAGS="$PIPE $DEBUG $O3 $IPA $GRAPHITE $DEVIRT $SEMANTIC $LTO $STRIP $FARCH"

      export CFLAGSFAT="$(printf -- "$CFLAGS" | sed "s/$LTO/& $FAT/")"
      export CFLAGSFATNOCOMMON="$(printf -- "$CFLAGSFAT" | sed "s/$STRIP /&$COMMON /")"

      export CFLAGSNOCOMMON="$(printf -- "$CFLAGS" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSNOCOMMONNOLTO="$(printf -- "$CFLAGS" | sed -e "s/$STRIP /&$COMMON /" -e "s/$LTO //")"

      export CFLAGSNOIPANOLTO="$(printf -- "$CFLAGS" | sed -e "s/$IPA //" -e "s/$LTO //")"

      export CFLAGSNOLTO="$(printf -- "$CFLAGS" | sed "s/$LTO //")"

      export CXXFLAGS="$CFLAGS"

      export LDFLAGS="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed $CFLAGS"

      export LDFLAGSNORELRO="-Wl,--strip-all -Wl,--as-needed $CFLAGS"
      ;;
    thompsoni | radiology)
      ;;
    *)
      $0 l s
      exit 1
      ;;
  esac
}

# Common bootstrap variables that are used in all stages (taken from the main
# Makefile located over at the main glaucus repository (which will soon be
# deprecated in favour of radula)).
rad_behave_bootstrap_variables() {
  # Originally GLAD and CERD belonged here but it appears that a better place
  # for them would be in the radula script itself as "global" variables.
  export BAKD=$GLAD/backup
  export CRSD=$GLAD/cross
  export LOGD=$GLAD/logs
  export SCRD=$GLAD/scripts
  export SRCD=$GLAD/sources
  export TMPD=$GLAD/temporary
  export TLCD=$GLAD/toolchain

  export PATH=$TLCD/bin:/usr/bin

  # pkgconf variables are only needed for the cross and chroot stages (the
  # toolchain stage won't use any of the pkgconf environment variables below).
  export PKG_CONFIG_PATH=$CRSD/usr/lib/pkgconfig:$CRSD/usr/share/pkgconfig
  export PKG_CONFIG_LIBDIR=$CRSD/usr/lib/pkgconfig:$CRSD/usr/share/pkgconfig
  export PKG_CONFIG_SYSROOT_DIR=$CRSD
  export PKG_CONFIG_SYSTEM_INCLUDE_PATH=$CRSD/usr/include
  export PKG_CONFIG_SYSTEM_LIBRARY_PATH=$CRSD/usr/lib

  # All commands here lack the verbosity flag because we intend to have two
  # modes of operation, and we're sticking with the silent one for now.
  export AUTORECONF='autoreconf -fis'
  export CHMOD='chmod -R'
  export CHOWN='chown -R'
  export LN='ln -fns'
  export MAKE='make -j1'
  # To prevent overlapping with the install() function in .ceras files, we add
  # the full path to the install command.
  export MKDIR='/usr/bin/install -d'
  export MV=mv
  export RM='rm -fr'
  export RSYNC='rsync -aHAXSx'
  export UMOUNT='umount -fqR'
}

# Bootstrap a cross-compiler toolchain targetting musl-libc
rad_behave_bootstrap_stage_toolchain_variables() {
  export TLOG=$LOGD/toolchain/$(ls -l $LOGD/toolchain | wc -l)
  export TSCR=$SCRD/toolchain
  export TTMP=$TMPD/toolchain

  export TSRC=$TTMP/sources
  export TBLD=$TTMP/builds

  export BLD=$($CERD/binutils/config.guess)
}

# The check script in the behave directory will soon have its functionality
# migrated to a function in radula.
rad_behave_bootstrap_stage_toolchain_check() {
  $SCRD/check musl &&
  $SCRD/check binutils &&
  $SCRD/check gmp &&
  $SCRD/check mpfr &&
  $SCRD/check mpc &&
  $SCRD/check isl &&
  $SCRD/check gcc
}

rad_behave_bootstrap_stage_toolchain_prepare() {
  $RM $CRSD &&
  $MKDIR $CRSD &&

  $RM $TBLD &&
  $MKDIR $TBLD &&

  $RM $TLCD &&
  $MKDIR $TLCD
}

# The construct script in the behave directory will soon have its functionality
# migrated to a function in radula.
rad_behave_bootstrap_stage_toolchain_construct() {
  $SCRD/construct toolchain musl-headers &&
  $SCRD/construct toolchain binutils &&
  $SCRD/construct toolchain gcc &&
  $SCRD/construct toolchain musl &&
  $SCRD/construct toolchain libgcc &&
  $SCRD/construct toolchain libstdc++-v3 &&
  $SCRD/construct toolchain libgomp
}

rad_behave_bootstrap_stage_toolchain_backup() {
  $RSYNC $CRSD $BAKD --delete &&

  $RSYNC $TLCD $BAKD --delete
}

# The '&&'s will be removed upon testing if the error/logging mechanisms are
# working as intended without them.
rad_behave_bootstrap_stage_toolchain() {
  rad_behave_bootstrap_variables &&

  rad_behave_bootstrap_stage_toolchain_variables &&
  rad_behave_bootstrap_stage_toolchain_check &&
  rad_behave_bootstrap_stage_toolchain_prepare &&

  rad_behave_bootstrap_stage_toolchain_construct &&

  rad_behave_bootstrap_stage_toolchain_backup
}

# Bootstrap a cross-compiled glaucus system
rad_behave_bootstrap_stage_cross() {
  :
}

# Bootstrap a cross-compiled chroot environment
rad_behave_bootstrap_stage_chroot() {
  :
}

# Source the configuration file in /etc/radula.conf
# Will soon be replaced with /etc/radula.conf (No forward slash for testing atm)
. etc/radula.conf

# Catch the quiet signal wherever it was.
# Currently the flag "require" wrongly turns the quiet signal on since the word
# "require" has a "q" in it. This needs to be fixed.
case "$@" in
  *q* | *-q* | *--quiet* | *--sleep*)
    sleep=1
    ;;
esac

# Our basic and portable argument parser
# Sets basic behavior variables and prints information only
# rad l q [g, s] doesn't work since list expects genome or species
while [ $# -ge 0 ]; do
  case $1 in
    # Don't call $0 b e just to exit with behave envenomate help message,
    # instead output that help message directly and let the user think radula is
    # operating in b e mode by default.
    '')
      rad_behave_envenomate_help
      exit 1
      ;;
    b | -b | --behave)
      case $2 in
        b | bootstrap)
          case $3 in
            r | require)
              rad_behave_bootstrap_require
              ;;
            c | chroot)
              [ $sleep -eq 0 ] && $0 b b r || $0 q b b r

              rad_open
              rad_open "Bootstrapping an $genome cross-compiled chroot environment..."

              rad_behave_bootstrap_arch
              rad_behave_bootstrap_flags
              ;;
            t | toolchain)
              [ $sleep -eq 0 ] && $0 b b r || $0 q b b r

              rad_open
              rad_open "Bootstrapping an $genome cross-compiler toolchain targetting musl libc..."

              rad_behave_bootstrap_arch

              rad_behave_bootstrap_stage_toolchain
              ;;
            x | cross)
              [ $sleep -eq 0 ] && $0 b b r || $0 q b b r

              rad_open
              rad_open "Bootstrapping an $genome cross-compiled glaucus $species system..."

              rad_behave_bootstrap_arch
              rad_behave_bootstrap_flags
              ;;
            *)
              rad_behave_bootstrap_help
              exit 1
              ;;
          esac
          ;;
        e | envenomate)
          # Don't check for the directory $CERD/$4 alone because when $4 is
          # empty it'll resolve to $CERD which does exist and will cause radula
          # to fail.
          if [ -f $CERD/$4/ceras ]; then
            . $CERD/$4/ceras

            case $3 in
              n | nom | name)
                rad_open "Name:        \t$nom"
                ;;
              v | ver | version)
                rad_open "Version:     \t$ver"
                ;;
              u | url | source)
                rad_open "Source:      \t$url"
                ;;
              s | sum | checksum | sha512sum)
                rad_open "sha512sum:   \t$sum"
                ;;
              y | cys | cyst | cysts)
                cys_len=$(printf "$cys" | wc -w)
                if [ $cys_len -gt 1 ]; then
                  rad_open "Cysts:       \t$(printf "$cys" | sed 's/ /, /g')"
                elif [ $cys_len -eq 1 ]; then
                  rad_open "Cyst:        \t$cys"
                else
                  rad_open 'Cyst:        \t~~'
                fi
                ;;
              c | cnt | concentrate | concentrates)
                cnt_len=$(printf "$cnt" | wc -w)
                if [ $cnt_len -gt 1 ]; then
                  rad_open "Concentrates:\t$(printf "$cnt" | sed 's/ /, /g')"
                elif [ $cnt_len -eq 1 ]; then
                  rad_open "Concentrate: \t$cnt"
                else
                  rad_open 'Concentrate: \t~~'
                fi
                ;;
              l | lic | license | licenses)
                lic_len=$(printf "$lic" | wc -w)
                if [ $lic_len -gt 1 ]; then
                  rad_open "Licenses:    \t$(printf "$lic" | tr '\n' ' ' | sed 's/ /, /g')"
                elif [ $lic_len -eq 1 ]; then
                  rad_open "License:     \t$lic"
                else
                  rad_open 'License:     \t~~'
                fi
                ;;
              '' | *)
                rad_behave_envenomate_help
                exit 1
                ;;
            esac

          elif [ -d $CERD/$3 ]; then
            . $CERD/$3/ceras

            for i in n v u s y c l; do
              [ $sleep -eq 0 ] && $0 b e $i $3 || $0 q b e $i $3
            done
          else
            rad_behave_envenomate_help
            exit 1
          fi
          ;;
        *)
          rad_behave_help
          exit 1
          ;;
      esac
      exit 0
      ;;
    bb | -bb)
      shift
      [ $sleep -eq 0 ] && $0 b b $@ || $0 q b b $@
      exit 0
      ;;
    be | -be)
      shift
      [ $sleep -eq 0 ] && $0 b e $@ || $0 q b e $@
      exit 0
      ;;
    g | -g | --genome)
      rad_open $genome
      exit 0
      ;;
    h | -h | --help)
      rad_help
      exit 0
      ;;
    l | -l | --list)
      case $2 in
        '')
          [ $sleep -eq 0 ] && $0 l g || $0 q l g

          rad_open

          [ $sleep -eq 0 ] && $0 l s || $0 q l s
          ;;
        g | genome)
          rad_open 'Genomes (Archs):'
          rad_open '\taarch64,          armv8-a,    arm64'
          rad_open '\tarmv6zk,          arm,        bcm2835'
          rad_open '\ti686,             i386,       x86'
          rad_open '\tpowerpc,          pmac32,     ppc'
          rad_open '\tpowerpc64,        g5,         ppc64'
          rad_open '\tpowerpc64le,      powernv,    ppc64le'
          rad_open '\triscv64,          rv64imafdc, riscv'
          rad_open '\tx86-64 (default), x86_64'
          ;;
        s | species)
          rad_open 'Species (Flags):'
          rad_open '\talbino,               libre'
          rad_open '\tatlanticus (default), performance'
          rad_open '\tbennettae,            size'
          rad_open '\tmarginatus,           sane'
          rad_open '\tthompsoni,            radiology'
          ;;
        *)
          rad_close 'Valid list options are: g, genome, s and species'
          ;;
      esac

      exit 0
      ;;
    q | -q | --quiet | --sleep)
      sleep=1
      ;;
    r | -r | --require)
      [ $sleep -eq 0 ] && $0 b b r || $0 q b b r
      exit 0
      ;;
    s | -s | --species)
      rad_open $species
      exit 0
      ;;
    v | -v | --version)
      rad_version
      exit 0
      ;;
    *)
      [ $sleep -eq 0 ] && $0 b e $@ || $0 q b e $@
      exit 0
      ;;
  esac

  shift
done
