#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

set -e
umask 022
unalias -a

#
# Default variables
#

bootstrap=0

genome=x86-64
species=atlanticus

sleep=0

# GLAucus Directory
GLAD=$PWD/..
# CERata Directory
CERD=$GLAD/cerata

#
# IO Functions
#

# Opens the radula (mouth)
rad_open() {
  [ $sleep = 0 ] && printf "\033[0;34m~~\033[0m $1\n" || printf "$1\n"
}

# Closes the radula (mouth)
# Use `exit 1` instead of rad_close when you don't want to print anything
rad_close() {
  [ $sleep = 0 ] && printf "\033[0;31m--\033[0m $1\n" || printf "$1\n"
  exit 1
}

#
# Information Functions
#

rad_version() {
  rad_open 'Copyright (c) 2018-2020, Firas Khalil Khana'
  rad_open 'Distributed under the terms of the ISC License'
  rad_open
  rad_open "$0 version 0.9.8 ($genome $species)"
}

rad_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 [ Options ]"
  rad_open
  rad_open 'Options:'
  rad_open '\tb, -b, --behave \tPerform any of the following behaviors:'
  rad_open '\t                \tbootstrap, envenomate (default)'
  rad_open
  rad_open '\tg, -g, --genome \tDisplay current genome'
  rad_open '\th, -h, --help   \tDisplay this help message'
  rad_open '\tl, -l, --list   \tList supported genomes and species'
  rad_open "\tq, -q, --quiet  \tDecrease the verbosity level and don't prefix"
  rad_open '\t                \tthe output with ~~'
  rad_open
  rad_open '\t       --sleep  \tSame as --quiet'
  rad_open '\ts, -s, --species\tDisplay current species'
  rad_open '\tv, -v, --version\tDisplay current version number'
}

rad_behave_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 [ b | -b | --behave ] [ Options ]"
  rad_open
  rad_open 'Options:'
  rad_open '\tb, bootstrap \tPerform bootstrap behavior'
  rad_open '\te, envenomate\tPerform envenomate behavior (default)'
  rad_open
  rad_open '\th, -h, --help\tDisplay this help message'
}

rad_behave_bootstrap_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 [ b | -b | --behave ] [ b | bootstrap ] [ Options ]"
  rad_open
  rad_open 'Options:'
  rad_open '\tc, clean     \tClean up while preserving sources and backups'
  rad_open '\td, distclean \tClean up everything'
  rad_open
  rad_open '\th, -h, --help\tDisplay this help message'
  rad_open
  rad_open '\tr, require   \tCheck if host has all required packages'
  rad_open '\tt, toolchain \tBootstrap a cross compiler toolchain'
  rad_open '\tx, cross     \tBootstrap a cross compiled glaucus system (default)'
}

rad_behave_envenomate_help() {
  rad_version

  rad_open
  rad_open 'Usage:'
  rad_open "\t$0 [ b | -b | --behave ] [ e | -e | --envenomate ] [ Options ] [ Cerata ]"
  rad_open
  rad_open 'Options:'
  rad_open "\tc, cnt, concentrate, concentrates\tDisplay ceras's concentrate(s)"
  rad_open
  rad_open '\th, -h, --help                    \tDisplay this help message'
  rad_open
  rad_open "\tl, lic, license, licenses        \tDisplay ceras's license(s)"
  rad_open "\tn, nom, name                     \tDisplay ceras's name"
  rad_open "\ts, sum, checksum, sha512sum      \tDisplay ceras's sha512sum"
  rad_open "\tu, url, source                   \tDisplay ceras's source"
  rad_open "\tv, ver, version                  \tDisplay ceras's version"
  rad_open "\ty, cys, cyst, cysts              \tDisplay ceras's cyst(s)"
}

#
# Common Behavior Functions
#

rad_behave_verify() {
  if [ $sleep -eq 0 ]; then
    printf "$sum $SRCD/$nom/$1" | sha512sum -c
  else
    printf "$sum $SRCD/$nom/$1" | sha512sum -c > /dev/null
  fi
}

rad_behave_fetch() {
  if [ $ver = git ]; then
    [ $sleep -eq 0 ] && git clone $url $SRCD/$nom || git clone -q $url $SRCD/$nom
  else
    $MKDIR $SRCD/$nom

    [ $sleep -eq 0 ] && curl -Lo $SRCD/$nom/$1 $url || curl -Lso $SRCD/$nom/$1 $url

    rad_behave_verify $1 || rad_close "ceras $nom: verify exited with status $?"

    [ $sleep -eq 0 ] && tar xvf $SRCD/$nom/$1 -C $SRCD/$nom || tar xf $SRCD/$nom/$l -C $SRCD/$nom
  fi
}

rad_behave_check() {
  . $CERD/$1/ceras

  if [ ! -d $SRCD/$nom ]; then
    rad_behave_fetch $(basename $url) || rad_close "ceras $nom: fetch exited with status $?"
  # In the case of a directory existing in $SRCD, and only if it's not a git
  # repository, then verify the tarball inside (if the tarball was previously
  # extracted, then verifying it won't matter much because the extracted
  # contents could've been tampered with (which is extremely unlikely) , and
  # this would require a reextraction in all cases which would slow down build
  # times by a bit (and not by a whole much because we're using zstd). The only
  # benefit that might come from reverifying an extracted tarball is this would
  # be if the tarball was already broken, but then again it was verified before
  # so how could that happen?
  elif [ $ver != git ]; then
    rad_behave_verify $(basename $url) || rad_close "ceras $nom: verify exited with status $?"
  fi
}

rad_behave_construct() {
  . $CERD/$2/ceras
  . $CERD/$nom/$1.ceras

  prepare || rad_close "ceras $nom: prepare exited with status $?"
  configure || rad_close "ceras $nom: configure exited with status $?"
  build || rad_close "ceras $nom: build exited with status $?"
  install || rad_close "ceras $nom: install exited with status $?"
}

rad_behave_envenomate() {
  $MKDIR $XCER/$1/sac
  $MKDIR $XCER/$1/venom

  rad_behave_construct cross $1

  $RSYNC $XCER/$1/sac/ $CRSD
}

rad_behave_gnu() {
  $RSYNC $CERD/binutils/config.$1 $2
}

rad_behave_patch() {
  [ $sleep -eq 0 ] && patch -p$1 -i $CERD/$2/patches/$3/$4.patch || patch -p$1 -si $CERD/$2/patches/$3/$4.patch
}

#
# Bootstrap Behavior Functions
#

rad_behave_bootstrap_require() {
  rad_open 'Checking if host has all required packages...'
  rad_open
  rad_open "bash:     \t$(bash --version | sed 1q | cut -d' ' -f4)"
  rad_open "bc:       \t$(bc --version | sed 1q | cut -d' ' -f2)"
  rad_open "binutils: \t$(ld --version | sed 1q | cut -d' ' -f4)"
  rad_open "bison:    \t$(bison --version | sed 1q | cut -d' ' -f4)"
  rad_open "bzip2:    \t$(bzip2 --version 2>&1 < /dev/null | sed 1q | cut -d' ' -f8 | sed s/,//)"
  rad_open "ccache:   \t$(ccache --version | sed 1q | cut -d' ' -f3)"
  rad_open "coreutils:\t$(ls --version | sed 1q | cut -d' ' -f4)"
  rad_open "curl:     \t$(curl --version | sed 1q | cut -d' ' -f2)"
  rad_open "diffutils:\t$(diff --version | sed 1q | cut -d' ' -f4)"
  rad_open "findutils:\t$(find --version | sed 1q | cut -d' ' -f4)"
  rad_open "g++:      \t$(g++ --version | sed 1q | cut -d' ' -f3)"
  rad_open "gawk:     \t$(gawk --version | sed 1q | cut -d' ' -f3 | sed s/,//)"
  rad_open "gcc:      \t$(gcc --version | sed 1q | cut -d' ' -f3)"
  rad_open "git:      \t$(git --version | cut -d' ' -f3)"
  rad_open "glibc:    \t$(/lib/libc.so.6 | sed 1q | cut -d' ' -f9 | sed s/\.$//)"
  rad_open "grep:     \t$(grep --version | sed 1q | cut -d' ' -f4)"
  rad_open "gzip:     \t$(gzip --version | sed 1q | cut -d' ' -f2)"
  rad_open "linux:    \t$(uname -r)"
  rad_open "lzip:     \t$(lzip --version | sed 1q | cut -d' ' -f2)"
  rad_open "m4:       \t$(m4 --version | sed 1q | cut -d' ' -f4)"
  rad_open "make:     \t$(make --version | sed 1q | cut -d' ' -f3)"
  rad_open "patch:    \t$(patch --version | sed 1q | cut -d' ' -f3)"
  rad_open "perl:     \t$(perl -V:version | cut -d"'" -f2)"
  rad_open "rsync:    \t$(rsync --version | sed 1q | cut -d' ' -f4)"
  rad_open "sed:      \t$(sed --version | sed 1q | cut -d' ' -f4)"
  rad_open "tar:      \t$(tar --version | sed 1q | cut -d' ' -f4)"
  rad_open "texinfo:  \t$(makeinfo --version | sed 1q | cut -d' ' -f4)"
  rad_open "xz:       \t$(xz --version | sed 1q | cut -d' ' -f4)"
  rad_open "zstd:     \t$(zstd --version | cut -d' ' -f7 | sed 's/,$//')"
}

rad_behave_bootstrap_initialize() {
  [ ! -d $BAKD ] && $MKDIR $BAKD
  
  [ ! -d $SRCD ] && $MKDIR $SRCD
}

# Architecture related variables explained (for rad_behave_bootstrap_arch):
#
# ARCH stands for the technically correct architecture (except for ones with a
# dash in them '-', then they get turned to underscores '_').
#
# CARCH stands for Cerata ARCH, which means options/flags that are related to a
# certain architecture and are passed in that ceras's configure function mostly
# (this includes all cerata with the exception of `gcc` as that has its own
# variable GCARCH).
#
# FARCH stands for Flags ARCH, which means options/flags that are related to a
# certain architecture and are passed in rad_behave_bootstrap_flags.
#
# GCARCH stands for Gcc Configuration ARCH, which means options/flags that are
# related to a certain architecture and are passed the `gcc` ceras configure
# function (In this regard, CARCH stands for cerata other than `gcc`).
#
# GPARCH stands for Gcc Patch ARCH, which refers to the architecture of the
# pure64 patch by glaucus applied to the `gcc` sources in the prepare function.
#
# MARCH stands for Musl ARCH, which refers to the closest architecture
# recognized by `musl`.
#
# LARCH stands for Linux ARCH, which refers to the closest architecture
# recognized by `linux`.
#
# LCARCH stands for Linux Configuration ARCH, which refers to the closest device
# with a similar architecture that's used to configure the kernel sources.
#
# LIARCH stands for Linux Image ARCH, which refers to the directory where
# `linux` stores its image file after it has been built.
rad_behave_bootstrap_arch() {
  case $genome in
    aarch64 | armv8-a | arm64)
      export ARCH=aarch64

      export CARCH=--with-gcc-arch=armv8-a

      export FARCH='-mabi=lp64 -mfix-cortex-a53-835769 -mfix-cortex-a53-843419 -march=armv8-a -mtune=generic'

      export GCARCH='--with-arch=armv8-a --with-abi=lp64 --enable-fix-cortex-a53-835769 --enable-fix-cortex-a53-843419'
      export GPARCH="rad_behave_patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=$ARCH

      export LARCH=arm64
      # LCARCH is empty because it uses the regular `defconfig`
      export LCARCH=
      export LIARCH=arch/$LARCH/boot/Image

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    armv6zk | arm | bcm2835)
      export ARCH=armv6zk

      export CARCH=

      export FARCH="-mabi=aapcs-linux -march=$ARCH -mtune=arm1176jzf-s -mcpu=arm1176jzf-s -mfpu=vfpv2 -mfloat-abi=hard"

      export GCARCH="--with-arch=$ARCH --with-tune=arm1176jzf-s --with-abi=aapcs-linux --with-fpu=vfpv2 --with-float=hard"
      # Doesn't need a pure64 patch for GCC since this isn't a 64 bit
      # architecture; hence, GPARCH is empty.
      export GPARCH=

      export MARCH=arm

      export LARCH=$MARCH
      # Optimize the linux configuration for the Raspberry Pi 1 Models A, B, B+,
      # the Compute Module, and the Raspberry Pi Zero.
      export LCARCH=bcm2835_
      export LIARCH=arch/$MARCH/boot/zImage

      export TGT=$ARCH-glaucus-linux-musleabihf
      ;;
    i686 | i386 | x86)
      # The i686 seems like the most logical 32-bit x86 architecture to optimize
      # for at this point.
      export ARCH=i686

      export CARCH=--with-gcc-arch=$ARCH

      export FARCH="-march=$ARCH -mtune=generic -mabi=sysv"

      export GCARCH="--with-arch=$ARCH --with-tune=generic"
      export GPARCH=

      # musl only knows i386, so we use that to configure it.
      export MARCH=i386

      # Same goes for the kernel.
      export LARCH=$MARCH
      export LCARCH=${MARCH}_
      export LIARCH=arch/x86/boot/bzImage

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    powerpc | pmac32 | ppc)
      export ARCH=powerpc

      export CARCH=

      export FARCH="-mcpu=$ARCH -msecure-plt"

      export GCARCH="--with-cpu=$ARCH --enable-secureplt --without-long-double-128"
      export GPARCH=

      export MARCH=$ARCH

      export LARCH=$ARCH
      export LCARCH=pmac32_
      export LIARCH=vmlinux

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    powerpc64 | g5 | ppc64)
      export ARCH=powerpc64

      export CARCH=

      export FARCH="-mcpu=$ARCH -mabi=elfv2"

      export GCARCH="--with-cpu=$ARCH --with-abi=elfv2"
      export GPARCH="rad_behave_patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=$ARCH

      export LARCH=powerpc
      # If you want to optimize the kernel configuration for the PlayStation 3,
      # you can use `altivec_` for LCARCH (which makes the kernel configure for
      # `altivec_defconfig`) which is also a powerpc64 architecture.
      export LCARCH=g5_
      export LIARCH=vmlinux

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    powerpc64le | powernv | ppc64le)
      export ARCH=powerpc64le

      export CARCH=

      export FARCH="-mcpu=$ARCH -mabi=elfv2"

      export GCARCH="--with-cpu=$ARCH --with-abi=elfv2"
      export GPARCH="rad_behave_patch 0 gcc glaucus 0001-pure64-for-powerpc64"

      export MARCH=powerpc64

      export LARCH=powerpc
      export LCARCH=powernv_
      export LIARCH=vmlinux

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    riscv64 | rv64imafdc | riscv)
      export ARCH=riscv64

      export CARCH=--with-gcc-arch=rv64imafdc

      export FARCH='-mabi=lp64d -march=rv64imafdc -mtune=rocket'

      export GCARCH='--with-arch=rv64imafdc --with-tune=rocket --with-abi=lp64d'
      export GPARCH="rad_behave_patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=$ARCH

      export LARCH=riscv
      export LCARCH=
      export LIARCH=arch/$LARCH/boot/Image

      export TGT=$ARCH-glaucus-linux-musl
      ;;
    x86-64 | x86_64)
      export ARCH=x86-64

      export CARCH=--with-gcc-arch=$ARCH

      export FARCH="-march=$ARCH -mtune=generic -mabi=sysv"

      export GCARCH="--with-arch=$ARCH --with-tune=generic"
      export GPARCH="rad_behave_patch 0 gcc glaucus 0001-pure64-for-$ARCH"

      export MARCH=x86_64

      export LARCH=$MARCH
      export LCARCH=${MARCH}_
      export LIARCH=arch/x86/boot/bzImage

      export TGT=$MARCH-glaucus-linux-musl
      ;;
    *)
      $0 l g
      exit 1
      ;;
  esac
}

rad_behave_bootstrap_flags() {
  # Common flags enabled in all species
  COMMON=-fcommon
  DEBUG=-g0
  FAT=-ffat-lto-objects
  LTO=-flto
  PIPE=-pipe
  STRIP=-s

  case $species in
    # albino (libre) is the libre version of atlanticus (performance)
    atlanticus | performance | albino | libre)
      export SPCS=atlanticus

      case $genome in
        x86-64 | x86_64)
          ALIGN=-malign-data=cacheline
          FPMATH=-mfpmath=both
          TLS=-mtls-dialect=gnu2
          ;;
      esac
      DEVIRT=-fdevirtualize-at-ltrans
      EXPAND=-fvariable-expansion-in-unroller
      FINITE=-fno-finite-math-only
      GCSE='-fgcse-sm -fgcse-las'
      GRAPHITE='-fgraphite-identity -floop-nest-optimize'
      IPA=-fipa-pta
      IRA=-fira-loop-pressure
      MERGE=-fmerge-all-constants
      OFAST=-Ofast
      OPENMP=-fopenmp
      PGO='-ftracer -funroll-loops'
      PLT=-fno-plt
      SEMANTIC=-fno-semantic-interposition
      SMS='-fmodulo-sched -fmodulo-sched-allow-regmoves'

      export CFLAGS="$PIPE $OPENMP $DEBUG $OFAST $SMS $GCSE $IRA $IPA $GRAPHITE $MERGE $DEVIRT $SEMANTIC $EXPAND $LTO $PGO $STRIP $PLT $FARCH $TLS $FPMATH $ALIGN"

      export CFLAGSFAT="$(printf -- "$CFLAGS" | sed "s/$LTO/& $FAT/")"
      export CFLAGSFATNOCOMMON="$(printf -- "$CFLAGSFAT" | sed "s/$STRIP /&$COMMON /")"

      export CFLAGSFINITE="$(printf -- "$CFLAGS" | sed "s/$OFAST/& $FINITE/")"

      export CFLAGSNOCOMMON="$(printf -- "$CFLAGS" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSNOCOMMONNOLTO="$(printf -- "$CFLAGS" | sed -e "s/$STRIP /&$COMMON /" -e "s/$LTO //")"

      export CFLAGSNOFPMATHNOLTO="$(printf -- "$CFLAGS" | sed -e "s/ $FPMATH//" -e "s/$LTO //")"

      export CFLAGSNOIPANOLTO="$(printf -- "$CFLAGS" | sed -e "s/$IPA //" -e "s/$LTO //")"

      export CFLAGSNOLTO="$(printf -- "$CFLAGS" | sed "s/$LTO //")"
      export CFLAGSNOLTONOOPENMPNOPLT="$(printf -- "$CFLAGSNOLTO" | sed -e "s/$OPENMP //" -e "s/$PLT //")"

      export CFLAGSNOOPENMP="$(printf -- "$CFLAGS" | sed "s/$OPENMP //")"

      export CXXFLAGS="$CFLAGS"

      export LDFLAGS="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed $CFLAGS"

      export LDFLAGSNOOPENMP="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed $CFLAGSNOOPENMP"

      export LDFLAGSNORELRO="-Wl,--strip-all -Wl,--as-needed $CFLAGS"
      ;;
    bennettae | size)
      export SPCS=bennettae

      AUNWIND=-fno-asynchronous-unwind-tables
      DSECTS=-fdata-sections
      EXCEPT=-fno-exceptions
      FSECTS=-ffunction-sections
      OMIT=-fomit-frame-pointer
      OS=-Os
      RTTI=-fno-rtti
      UNWIND=-fno-unwind-tables

      export CFLAGS="$PIPE $RTTI $DEBUG $OS $OMIT $LTO $FSECTS $DSECTS $STRIP $EXCEPT $UNWIND $AUNWIND $FARCH"

      export CFLAGSFAT="$(printf -- "$CFLAGS" | sed "s/$LTO/& $FAT/")"
      export CFLAGSFATNOCOMMON="$(printf -- "$CFLAGSFAT" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSFATNODSECTS="$(printf -- "$CFLAGSFAT" | sed "s/$DSECTS //")"

      export CFLAGSNODSECTS="$(printf -- "$CFLAGS" | sed "s/$DSECTS //")"

      export CFLAGSNOCOMMON="$(printf -- "$CFLAGS" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSNOCOMMONNOLTO="$(printf -- "$CFLAGS" | sed -e "s/$STRIP /&$COMMON /" -e "s/$LTO //")"

      export CFLAGSNOLTO="$(printf -- "$CFLAGS" | sed "s/$LTO //")"

      export CXXFLAGS="$CFLAGS"

      export LDFLAGS="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed -Wl,--gc-sections $CFLAGS"

      export LDFLAGSNORELRO="-Wl,--strip-all -Wl,--as-needed $CFLAGS"
      ;;
    # thompsoni (radiology) is based on marginatus (sane)
    marginatus | sane | thompsoni | radiology)
      export SPCS=marginatus

      DEVIRT=-fdevirtualize-at-ltrans
      GRAPHITE='-fgraphite-identity -floop-nest-optimize'
      IPA=-fipa-pta
      O3=-O3
      SEMANTIC=-fno-semantic-interposition

      export CFLAGS="$PIPE $DEBUG $O3 $IPA $GRAPHITE $DEVIRT $SEMANTIC $LTO $STRIP $FARCH"

      export CFLAGSFAT="$(printf -- "$CFLAGS" | sed "s/$LTO/& $FAT/")"
      export CFLAGSFATNOCOMMON="$(printf -- "$CFLAGSFAT" | sed "s/$STRIP /&$COMMON /")"

      export CFLAGSNOCOMMON="$(printf -- "$CFLAGS" | sed "s/$STRIP /&$COMMON /")"
      export CFLAGSNOCOMMONNOLTO="$(printf -- "$CFLAGS" | sed -e "s/$STRIP /&$COMMON /" -e "s/$LTO //")"

      export CFLAGSNOIPANOLTO="$(printf -- "$CFLAGS" | sed -e "s/$IPA //" -e "s/$LTO //")"

      export CFLAGSNOLTO="$(printf -- "$CFLAGS" | sed "s/$LTO //")"

      export CXXFLAGS="$CFLAGS"

      export LDFLAGS="-Wl,--strip-all -Wl,-z,now,-z,relro -Wl,--as-needed $CFLAGS"

      export LDFLAGSNORELRO="-Wl,--strip-all -Wl,--as-needed $CFLAGS"
      ;;
    *)
      $0 l s
      exit 1
      ;;
  esac
}

# BAKD = BAcKup Directory
# CRSD = CRoSs Directory
# SRCD = SouRCes Directory
# TMPD = TeMPorary Directory
# TLCD = TooLChain Directory
rad_behave_bootstrap_variables() {
  export BAKD=$GLAD/backup
  export CRSD=$GLAD/cross
  export SRCD=$GLAD/sources
  export TMPD=$GLAD/temporary
  export TLCD=$GLAD/toolchain

  export PATH=$TLCD/bin:/usr/bin

  if [ $sleep -eq 0 ]; then
    export AUTORECONF='autoreconf -fvis'
    export CHMOD='chmod -Rv'
    export CHOWN='chown -Rv'
    export LN='ln -fnsv'
    export MAKE='make -j1 V=1'
    # Full path to not overlap with the install() function in .ceras files
    export MKDIR='/usr/bin/install -dv'
    export MV='mv -v'
    export RM='rm -frv'
    export RSYNC='rsync -vaHAXSx'
    export UMOUNT='umount -fqRv'
  else
    export AUTORECONF='autoreconf -fis'
    export CHMOD='chmod -R'
    export CHOWN='chown -R'
    export LN='ln -fns'
    export MAKE='make -j1'
    export MKDIR='/usr/bin/install -d'
    export MV=mv
    export RM='rm -fr'
    export RSYNC='rsync -aHAXSx'
    export UMOUNT='umount -fqR'
  fi
}

# Only for use in cross
rad_behave_bootstrap_pkg_config_variables() {
  # pkgconf and pkg-config don't respect the provided sysroot (it doesn't get
  # automatically prefixed to PATH and LIBDIR)
  export PKG_CONFIG_PATH=$CRSD/usr/lib/pkgconfig:$CRSD/usr/share/pkgconfig
  export PKG_CONFIG_LIBDIR=$CRSD/usr/lib/pkgconfig:$CRSD/usr/share/pkgconfig
  export PKG_CONFIG_SYSROOT_DIR=$CRSD
  export PKG_CONFIG_SYSTEM_INCLUDE_PATH=$CRSD/usr/include
  export PKG_CONFIG_SYSTEM_LIBRARY_PATH=$CRSD/usr/lib
}

#
# Toolchain Stage Functions
#

# TTMP = Toolchain TeMPorary Directory
# TBLD = Toolchain temporary BuiLDs Directory
# TSRC = Toolchain temporary SouRCes Directory
rad_behave_bootstrap_stage_toolchain_variables() {
  export TTMP=$TMPD/toolchain

  export TSRC=$TTMP/sources
  export TBLD=$TTMP/builds

  export BLD=$($CERD/binutils/config.guess)
}

rad_behave_bootstrap_stage_toolchain_check() {
  rad_behave_check musl
  rad_behave_check binutils
  rad_behave_check gmp
  rad_behave_check mpfr
  rad_behave_check mpc
  rad_behave_check isl
  rad_behave_check gcc
}

rad_behave_bootstrap_stage_toolchain_prepare() {
  $RM $CRSD
  $MKDIR $CRSD

  $RM $TBLD
  $MKDIR $TBLD

  [ ! -d $TSRC ] && $MKDIR $TSRC

  $RM $TLCD
  $MKDIR $TLCD
}

rad_behave_bootstrap_stage_toolchain_construct() {
  rad_behave_construct toolchain musl-headers
  rad_behave_construct toolchain binutils
  rad_behave_construct toolchain gcc
  rad_behave_construct toolchain musl
  rad_behave_construct toolchain libgcc
  rad_behave_construct toolchain libstdc++-v3
  # Only for atlanticus (performance) and albino (libre)
  rad_behave_construct toolchain libgomp
}

rad_behave_bootstrap_stage_toolchain_backup() {
  $RSYNC $CRSD $BAKD --delete
  $RSYNC $TLCD $BAKD --delete
}

rad_behave_bootstrap_stage_toolchain() {
  rad_behave_bootstrap_stage_toolchain_variables
  rad_behave_bootstrap_stage_toolchain_check
  rad_behave_bootstrap_stage_toolchain_prepare

  rad_behave_bootstrap_stage_toolchain_construct

  rad_behave_bootstrap_stage_toolchain_backup
}

# Experimental release function
rad_behave_bootstrap_stage_toolchain_release() {
  $RSYNC $BAKD/toolchain /tmp --delete

  rad_behave_bootstrap_stage_toolchain_variables

  $RM /tmp/toolchain/lib64

  find /tmp/toolchain -name *.la -delete

  strip -gv /tmp/toolchain/lib/* || true
  /usr/bin/strip --strip-unneeded -v /tmp/toolchain/bin/* || true

  $RM /tmp/toolchain/share/doc
  $RM /tmp/toolchain/share/info
  $RM /tmp/toolchain/share/man

  /usr/bin/tar -I '/usr/bin/zstd -22 --ultra --long=31 -T0' -cvf toolchain-$(date +%d%m%Y).tar.zstd /tmp/toolchain
}

#
# Cross Stage Functions
#

# XTMP = cross TeMPorary Directory
# XBLD = Toolchain temporary BuiLDs Directory
# XCER = Toolchain temporary BuiLDs Directory
# XSRC = Toolchain temporary SouRCes Directory
rad_behave_bootstrap_stage_cross_variables() {
  export XTMP=$TMPD/cross

  export XBLD=$XTMP/builds
  export XCER=$XTMP/cerata
  export XSRC=$XTMP/sources

  # NATIVECC and NATIVECXX were superceded by HOSTCC and HOSTCXX.
  #
  # HOSTCC and HOSTCXX are optional (used in netbsd-curses for nbperf and tic).
  export HOSTCC=gcc
  export HOSTCXX=g++

  export AR=$TGT-gcc-ar
  export AS=$TGT-as
  export CC=$TGT-gcc
  export CPP="$TGT-gcc -E"
  export CXX=$TGT-g++
  export LD=$TGT-ld
  export NM=$TGT-gcc-nm
  export OBJCOPY=$TGT-objcopy
  export OBJDUMP=$TGT-objdump
  export RANLIB=$TGT-gcc-ranlib
  export READELF=$TGT-readelf
  export SIZE=$TGT-size
  export STRINGS=$TGT-strings
  export STRIP=$TGT-strip

  export BLD=$($CERD/binutils/config.guess)
}

rad_behave_bootstrap_stage_cross_check() {
  rad_behave_check linux
  rad_behave_check shadow
  rad_behave_check libressl
  rad_behave_check toybox
  rad_behave_check netbsd-curses
  rad_behave_check procps-ng
  rad_behave_check mksh
  rad_behave_check dash
  rad_behave_check util-linux
  rad_behave_check e2fsprogs
  rad_behave_check eudev
}

rad_behave_bootstrap_stage_cross_prepare() {
  $RSYNC $BAKD/cross $GLAD --delete
  $RSYNC $BAKD/toolchain $GLAD --delete

  [ -d $XBLD ] && $RM $XBLD
  [ ! -d $XBLD ] && $MKDIR $XBLD

  [ -d $XCER ] && $RM $XCER
  [ ! -d $XCER ] && $MKDIR $XCER

  [ ! -d $XSRC ] && $MKDIR $XSRC

  $MKDIR $CRSD/etc

  # Do we need more groups for eudev?
  printf 'root:x:0:
  tty:x:1:
  disk:x:2:
  audio:x:3:
  video:x:4:\n' > $CRSD/etc/group

  printf '127.0.0.1 localhost glaucus\n' > $CRSD/etc/hosts

  # Will switch to oksh
  printf 'root::0:0:root:/root:/usr/bin/mksh\n' > $CRSD/etc/passwd

  $RM $CRSD/var
  $MKDIR $CRSD/var/lib
  $MKDIR $CRSD/var/lib/urandom
  $MKDIR $CRSD/var/log
}

rad_behave_bootstrap_stage_cross_envenomate() {
  rad_behave_envenomate linux-headers
  rad_behave_envenomate shadow
  rad_behave_envenomate libressl
  rad_behave_envenomate toybox
  rad_behave_envenomate netbsd-curses
  rad_behave_envenomate procps-ng
  # Will switch to oksh
  rad_behave_envenomate mksh
  rad_behave_envenomate dash
  rad_behave_envenomate util-linux
  rad_behave_envenomate e2fsprogs
  rad_behave_envenomate eudev
  #rad_behave_envenomate linux
}

rad_behave_bootstrap_stage_cross_configure() {
  printf '/dev/sda1 / ext4 defaults 0 1\n' > $CRSD/etc/fstab

  printf 'export PS1="[\033[0;44m\u@\h\033[0m:\033[1m\w\033[0m]$ "
  export HISTFILE=$HOME/.ksh_history\n' > $CRSD/etc/profile

  # Will switch to oksh
  printf '/usr/bin/dash
  /usr/bin/ksh
  /usr/bin/mksh
  /usr/bin/rksh
  /usr/bin/sh\n' > $CRSD/etc/shells
}

rad_behave_bootstrap_stage_cross_strip() {
  find $CRSD/etc -type d -empty -delete

  find $CRSD/usr -name *.a -type f -exec strip -gv {} \;
  find $CRSD/usr \( -name *.so* -a ! -name *dbg \) -type f -exec strip \
    --strip-unneeded -v {} \;
  find $CRSD/usr -type f -exec strip -sv {} \;
  find $CRSD/usr -name *.la -delete

  $RM $CRSD/usr/lib/charset.alias
}

rad_behave_bootstrap_stage_cross() {
  rad_behave_bootstrap_stage_cross_variables
  rad_behave_bootstrap_stage_cross_check
  rad_behave_bootstrap_stage_cross_prepare

  rad_behave_bootstrap_stage_cross_envenomate

  rad_behave_bootstrap_stage_cross_configure
  rad_behave_bootstrap_stage_cross_strip
}

rad_behave_bootstrap_stage_cross_img() {
  NAME=$PWD/../glaucus.img
  SIZE=128M
  # Apparently it won't find losetup without this, and I'm too lazy to debug
  # this, so we'll leave it for now...
  export PATH=/usr/sbin:/usr/bin
  LOOP=$(losetup -f)

  #$RM $NAME
  # We're creating a raw image
  qemu-img create -f raw $NAME $SIZE
  # We're using the mbr.bin provided by SYSLINUX, and is written to the first
  # 440 bytes of our image above (don't change the bs/count).
  dd if=other/mbr.bin of=$NAME conv=notrunc bs=440 count=1

  # Using parted without prompting for user interaction.
  parted -s $NAME mklabel msdos
  # Defaulting to ext4 (see rad_behave_bootstrap_stage_cross_configure for the
  # comment regarding fstab).
  parted -s -a none $NAME mkpart primary ext4 0 $SIZE
  parted -s -a none $NAME set 1 boot on

  # Detach all loop devices if any (We can either rely on $LOOP providing an
  # empty loop device for use, or detach all loop devices and start from loop0,
  # and I think the former is better since the user might have loop devices
  # already attached).
  losetup -D
  losetup $LOOP $NAME

  # Needed for the partitioning of the image (notifies the kernel).
  partx -a $LOOP
  mkfs.ext4 $(printf $LOOP)p1

  mount $(printf $LOOP)p1 /mnt/loop

  # Remove this empty directory
  $RM /mnt/loop/lost+found

  # Create the essential vkfs directories
  $MKDIR /mnt/loop/dev
  $MKDIR /mnt/loop/proc
  $MKDIR /mnt/loop/run
  $MKDIR /mnt/loop/sys

  # Special permissions directories
  $MKDIR -m 0750 /mnt/loop/root
  $MKDIR -m 1777 /mnt/loop/tmp

  # Copy the cross compiled system we just built
  $RSYNC ../cross/boot /mnt/loop
  $RSYNC ../cross/etc /mnt/loop
  $RSYNC ../cross/usr /mnt/loop
  $RSYNC ../cross/var /mnt/loop

  # Essential symlinks that can't be removed since many software depend on their
  # existence (make, perl, python, )
  $LN usr/bin /mnt/loop/bin
  $LN usr/lib /mnt/loop/lib

  $MKDIR /mnt/loop/boot/extlinux
  $RSYNC other/extlinux.conf /mnt/loop/boot/extlinux

  $CHOWN -R 0:0 /mnt/loop

  extlinux --install /mnt/loop/boot/extlinux

  # Clean up
  $UMOUNT /mnt/loop
  partx -d $LOOP
  losetup -d $LOOP
}

rad_behave_bootstrap_clean() {
  [ -d $CRSD ] && $RM $CRSD

  [ -d $TLCD ] && $RM $TLCD
}

rad_behave_bootstrap_distclean() {
  [ -d $BAKD ] && $RM $BAKD

  [ -d $SRCD ] && $RM $SRCD

  [ -d $TMPD ] && $RM $TMPD

  rad_behave_bootstrap_clean
}

#
# Main
#

if [ -f /etc/radula.conf ]; then
  . /etc/radula.conf
elif [ -f /etc/rad.conf ]; then
  . /etc/rad.conf
fi

# Tip: prefix or postfix your options with the letter `q` to correctly silence
# radula.
#
# Currently the flag "require" wrongly turns the quiet signal on since the word
# "require" has a "q" in it. This needs to be fixed.
case "$@" in
  *q* | *-q* | *--quiet* | *--sleep*)
    sleep=1
    ;;
esac

# rad l q [g, s] doesn't work since list expects genome or species
while [ $# -ge 0 ]; do
  case $1 in
    '')
      rad_help
      exit 1
      ;;
    b | -b | --behave)
      case $2 in
        b | bootstrap)
          case $3 in
            c | clean)
              rad_behave_bootstrap_variables

              rad_behave_bootstrap_clean
              ;;
            d | distclean)
              rad_behave_bootstrap_variables

              rad_behave_bootstrap_distclean
              ;;
            h | -h | --help)
              rad_behave_bootstrap_help
              ;;
            i | img | image)
              rad_behave_bootstrap_variables

              rad_behave_bootstrap_stage_cross_img
              ;;
            r | require)
              rad_behave_bootstrap_require
              ;;
            t | toolchain)
              [ $sleep -eq 0 ] && $0 b b r || $0 q b b r

              rad_open
              rad_open "Bootstrapping an $genome cross-compiler toolchain targetting musl libc..."

              rad_behave_bootstrap_variables
              rad_behave_bootstrap_initialize

              # No rad_behave_bootstrap_flags optimizations for the toolchain.
              rad_behave_bootstrap_arch

              rad_behave_bootstrap_stage_toolchain

              rad_open
              rad_open "Successfully bootstrapped an $genome cross-compiler toolchain targetting musl libc!"
              ;;
            x | cross)
              [ $sleep -eq 0 ] && $0 b b r || $0 q b b r

              rad_open
              rad_open "Bootstrapping an $genome cross-compiled glaucus $species system..."

              rad_behave_bootstrap_variables
              rad_behave_bootstrap_pkg_config_variables

              rad_behave_bootstrap_arch
              rad_behave_bootstrap_flags

              rad_behave_bootstrap_stage_cross

              rad_open
              rad_open "Successfully bootstrapped an $genome cross-compiled glaucus $species system!"
              ;;
            *)
              rad_behave_bootstrap_help
              exit 1
              ;;
          esac
          ;;
        e | envenomate)
          # Don't check for the directory $CERD/$4 alone because when $4 is
          # empty it'll resolve to $CERD which does exist and will cause radula
          # to fail.
          if [ -f $CERD/$4/ceras ]; then
            . $CERD/$4/ceras

            case $3 in
              n | nom | name)
                rad_open "Name:        \t$nom"
                ;;
              v | ver | version)
                rad_open "Version:     \t$ver"
                ;;
              u | url | source)
                rad_open "Source:      \t$url"
                ;;
              s | sum | checksum | sha512sum)
                rad_open "sha512sum:   \t$sum"
                ;;
              y | cys | cyst | cysts)
                cys_len=$(printf "$cys" | wc -w)
                if [ $cys_len -gt 1 ]; then
                  rad_open "Cysts:       \t$(printf "$cys" | sed 's/ /, /g')"
                elif [ $cys_len -eq 1 ]; then
                  rad_open "Cyst:        \t$cys"
                else
                  rad_open 'Cyst:        \t~~'
                fi
                ;;
              c | cnt | concentrate | concentrates)
                cnt_len=$(printf "$cnt" | wc -w)
                if [ $cnt_len -gt 1 ]; then
                  rad_open "Concentrates:\t$(printf "$cnt" | sed 's/ /, /g')"
                elif [ $cnt_len -eq 1 ]; then
                  rad_open "Concentrate: \t$cnt"
                else
                  rad_open 'Concentrate: \t~~'
                fi
                ;;
              l | lic | license | licenses)
                lic_len=$(printf "$lic" | wc -w)
                if [ $lic_len -gt 1 ]; then
                  rad_open "Licenses:    \t$(printf "$lic" | tr '\n' ' ' | sed 's/ /, /g')"
                elif [ $lic_len -eq 1 ]; then
                  rad_open "License:     \t$lic"
                else
                  rad_open 'License:     \t~~'
                fi
                ;;
              *)
                rad_behave_envenomate_help
                exit 1
                ;;
            esac

          elif [ ! -z $3 ] && [ "$3" != h ] && [ -d $CERD/$3 ]; then
            . $CERD/$3/ceras

            for i in n v u s y c l; do
              [ $sleep -eq 0 ] && $0 b e $i $3 || $0 q b e $i $3
            done
          elif [ "$3" = h ]; then
            rad_behave_envenomate_help
            exit 0
          else
            rad_behave_envenomate_help
            exit 1
          fi
          ;;
        h | -h | --help)
          rad_behave_help
          exit 0
          ;;
        *)
          rad_behave_help
          exit 1
          ;;
      esac
      exit 0
      ;;
    g | -g | --genome)
      rad_open $genome
      exit 0
      ;;
    h | -h | --help)
      rad_help
      exit 0
      ;;
    l | -l | --list)
      rad_version

      rad_open
      rad_open 'Genomes (Architectures):'
      rad_open '\taarch64,     armv8-a,    arm64'
      rad_open '\tarmv6zk,     arm,        bcm2835'
      rad_open '\ti686,        i386,       x86'
      rad_open '\tpowerpc,     pmac32,     ppc'
      rad_open '\tpowerpc64,   g5,         ppc64'
      rad_open '\tpowerpc64le, powernv,    ppc64le'
      rad_open '\triscv64,     rv64imafdc, riscv'
      rad_open '\tx86-64,      x86_64'
      rad_open
      rad_open 'Species (Flags):'
      rad_open '\talbino,     libre'
      rad_open '\tatlanticus, performance'
      rad_open '\tbennettae,  size'
      rad_open '\tmarginatus, sane'
      rad_open '\tthompsoni,  radiology'
      exit 0
      ;;
    s | -s | --species)
      rad_open $species
      exit 0
      ;;
    v | -v | --version)
      rad_version
      exit 0
      ;;
  esac

  shift
done
