#!/bin/sh -e

# Copyright (c) 2018-2020, Firas Khalil Khana
# Distributed under the terms of the ISC License

. $CERD/$2/ceras &&
. $CERD/$nom/$1.ceras &&

$MKDIR $FLOG/$nom/prepare &&
prepare || #> $FLOG/$nom/prepare/out.log 2> $FLOG/$nom/prepare/err.log ||
$SCRD/die $1 $nom prepare $? ||
exit

$MKDIR $FLOG/$nom/configure &&
configure || #> $FLOG/$nom/configure/out.log 2> $FLOG/$nom/configure/err.log ||
$SCRD/die $1 $nom configure $? ||
exit

$MKDIR $FLOG/$nom/build &&
build || #> $FLOG/$nom/build/out.log 2> $FLOG/$nom/build/err.log ||
$SCRD/die $1 $nom build $? ||
exit

$MKDIR $FLOG/$nom/install &&
install || #> $FLOG/$nom/install/out.log 2> $FLOG/$nom/install/err.log ||
$SCRD/die $1 $nom install $? ||
exit
